export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const GET_MEMBERS_SUCCESS = 'DELETE_TEAM_SUCCESS';
